# Generated by Django 4.1.2 on 2023-05-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_profile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
