# Generated by Django 4.1.2 on 2023-06-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_remove_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Physical_test_Fail',
            field=models.BooleanField(default=False),
        ),
    ]
