# Generated by Django 4.1.2 on 2023-06-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_profile_physical_test_fail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test_failed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
